name: "Build"
on:
  push:
    branches:
      - main

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   
    - name: "Publish Firefox"
      uses: trmcnvn/firefox-addon@v1
      with:
        xpi: build/my-addon.xpi
        manifest: src/manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}
