name: "Build Extension"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        
    outputs:
      target:
        description: "The output build target"
        value: ${{ jobs.build.outputs.target }}
  
jobs:
  build:
  runs-on: ubuntu-latest
  
   outputs:
    target: ${{ steps.web_ext_build.outputs.target }}
   
   steps:
    - name: "Checkout"
      uses: actions/checkout@v3
      
   # Build extention
    - name: "web-ext build"
      id: ext_build
      if: ${{ inputs.version }}
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: src
        filename: "${{ inputs.version }}.xpi"
    
    # Check building
    - name: Check building
      run: |
        ls -la web-ext-artifacts
        
    - name: Archive extension
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.version }}
        path: ${{ steps.ext_build.outputs.target }}
