name: "Build"
on:
  push:
    tags:
      - v*
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: "Checkout"
      uses: actions/checkout@v1
      
   # Build extention
    - name: "web-ext build"
      id: web-ext-build
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: src
        filename: "{name}-{version}.xpi"

    # Check building
    - name: Check building
      run: |
        ls -la web-ext-artifacts

    # Create  Release
    - name: "Create Release"
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ steps.get_version.outputs.EXTENSION_VERSION }}
          files: ${{ steps.web-ext-build.outputs.target }}
