name: "Build"
on:
  push:
    branches:
      - main

jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: trmcnvn/firefox-addon@v1
      with:
        # uuid is only necessary when updating an existing addon,
        # omitting it will create a new addon
        uuid: '{7b312f5e-9680-436b-acc1-9b09f60e8aaa}'
        xpi: build/my-addon.xpi
        manifest: src/manifest.json
        api-key: ${{ secrets.AMO_SIGN_KEY }}
        api-secret: ${{ secrets.AMO_SIGN_SECRET }}
