name: "Build Extension"

on:
  workflow_call:
    inputs:
      version:
        description: "A version number of the extension."
        required: true
        type: string
        
      state:
        description: "A state of the extension. Suppose there are two states: signed and unsigned." 
        required: false
        type: string
        default: "unsigned"
      
   
    outputs:
      target:
        description: "The output build target"
        value: ${{ jobs.build.outputs.target }}
        
      filename:
        description: "The output filename"
        value: ${{ jobs.build.outputs.filename }}
  
jobs:
  build:
   runs-on: ubuntu-latest
  
   outputs:
    target: ${{ steps.ext_build.outputs.target }}
    filename: ${{ steps.set_name.outputs.filename }}
   
   steps:
    - name: "Checkout"
      uses: actions/checkout@v3
    
    - name: "Set extension name"
      id: set_name
      run: echo "::set-output name=filename::${{ inputs.version }}-${{ inputs.state }}.xpi"
      
   # Build extention
    - name: "web-ext build"
      id: ext_build
      if: ${{ inputs.version != '' }}
      uses: kewisch/action-web-ext@v1
      with:
        cmd: build
        source: src
        filename: "${{ steps.set_name.outputs.filename }}"
    
    # Check building
    - name: Check building
      run: |
        ls -la web-ext-artifacts
        
    - name: Archive extension
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.version }}
        path: ${{ steps.ext_build.outputs.target }}
