name: "Release"

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    uses: ./.github/workflows/version.yml
    
  build:
    runs-on: ubuntu-latest
    needs: extract_version
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Show release version
        run: echo $({ needs.extract_version.outputs.version  })
