name: "Release"

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    uses: ./.github/workflows/version.yml
  
  ext_build:
    needs: extract_version
    if: ${{ needs.extract_version.outputs.version != '' }}
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.extract_version.outputs.version }}
    
  
  release:
    runs-on: ubuntu-latest
    
    needs: [ extract_version, ext_build ]
    
    env:
      EXTENSION_NAME: "${{ needs.extract_version.outputs.version }}/${{  needs.ext_build.outputs.filename }}"
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Download Artifact
        id: download_artifact
        uses: actions/download-artifact@v3
        with:
          path: ./
      
      # Check downloaded artifact
      - run: ls -R
      
      # Create  Release
      - name: "Create Release"
        if: hashFiles('${{ env.EXTENSION_NAME }}') != ''
        uses: softprops/action-gh-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{  needs.extract_version.outputs.version }}
            files: "${{ env.EXTENSION_NAME }}"
