name: "Release"

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    uses: ./.github/workflows/version.yml
    
  build:
    runs-on: ubuntu-latest
    
    needs: [ extract_version ]
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Show release version
        run: echo "Extension version is ${{ needs.extract_version.outputs.version }}"
      
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          version: ${{ needs.extract_version.outputs.version }}
