name: "Release"

on:
  push:
    branches:
      - main

jobs:
  extract_version:
    uses: ./.github/workflows/version.yml
  
  ext_build:
    needs: extract_version
    if: ${{ needs.extract_version.outputs.version != '' }}
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.extract_version.outputs.version }}
    
  
  release:
    runs-on: ubuntu-latest
    
    needs: [ extract_version, ext_build ]
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Show release version
        run: echo "Extension version is ${{ needs.extract_version.outputs.version }}"
      - run: ls .
      
      - name: Download Artifact
        id: download_artifact
        uses: actions/download-artifact@v3
        with:
          name: "${{ needs.extract_version.outputs.version }}.xpi"
          path: ${{ github.workspace }}/build/${{ needs.extract_version.outputs.version }}.xpi
      
      - run: |
          ls "${{ github.workspace }}/build/"
          ls .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ needs.extract_version.outputs.version }}
            files: ${{ github.workspace }}/build/${{ needs.extract_version.outputs.version }}.xpi
