name: Get Version

on:
  workflow_call:
    outputs:
      version:
        description: "The extracted version"
        value: ${{ jobs.get_version.outputs.version }}

jobs:
  get_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.extract_step.outputs.version }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      
      - name: Extract version from Manifest
        id: extract_step
        run: echo "::set-output name=version::v$(cat src/manifest.json | sed -nr 's/(\"version\":).*\"([0-9]+(\.[0-9]+)*)\".$/\2/p' | tr -d '[:space:]')"
